### ISSUE TITLE
Method SettingsController::assignToPanels does not exist.

### ISSUE THREAD

**Issue by zippbl4** [optimistdigital/nova-settings#2]
```
[2019-10-24 15:38:01] local.ERROR: Method OptimistDigital\NovaSettings\Http\Controllers\SettingsController::assignToPanels does not exist. {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Method OptimistDigital\\NovaSettings\\Http\\Controllers\\SettingsController::assignToPanels does not exist. at /var/www/html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:68)
[stacktrace]
#0 /var/www/html/test1/vendor/optimistdigital/nova-settings/src/Http/Controllers/SettingsController.php(22): Illuminate\\Routing\\Controller->__call('assignToPanels', Array)
#1 [internal function]: OptimistDigital\\NovaSettings\\Http\\Controllers\\SettingsController->get(Object(Illuminate\\Http\\Request))
#2 /var/www/html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
```

Laravel 5.8.35
Nova 2.0.6

**Comment by Tarpsvo** [comment]
Oopsie, it appears you need Laravel Nova 2.0.8 or later for this to work. The `assignToPanels` method was introduced in 2.0.8. I'll add that to the README.
